change to 2022.11.1

diff --git a/package/ssdp-responder/S50ssdpd b/package/ssdp-responder/S50ssdpd
--- a/package/ssdp-responder/S50ssdpd
+++ b/package/ssdp-responder/S50ssdpd
@@ -1,32 +1,25 @@
 #!/bin/sh
 
-DAEMON=ssdpd
-PIDFILE=/var/run/$DAEMON.pid
-CFGFILE=/etc/default/$DAEMON
+NAME=ssdpd
+PIDFILE=/var/run/$NAME.pid
+DAEMON=/usr/sbin/$NAME
+CFGFILE=/etc/default/$NAME
 
 DAEMON_ARGS=""
 
 # Read configuration variable file if it is present
-# shellcheck source=/dev/null
-[ -r "$CFGFILE" ] && . "$CFGFILE"
+[ -f $CFGFILE ] && . $CFGFILE
 
-# shellcheck disable=SC2086
 start() {
-	printf 'Starting %s: ' "$DAEMON"
-	if start-stop-daemon -S -q -p "$PIDFILE" -x "$DAEMON" -- $DAEMON_ARGS; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
+	printf 'Starting %s: ' "$NAME"
+	start-stop-daemon -S -q -p $PIDFILE -x $DAEMON -- $DAEMON_ARGS
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 stop() {
-	printf 'Stopping %s: ' "$DAEMON"
-	if start-stop-daemon -K -q -p "$PIDFILE" -x "$DAEMON"; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
+	printf 'Stopping %s: ' "$NAME"
+	start-stop-daemon -K -q -p $PIDFILE -x $DAEMON
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 }
 
 restart() {
@@ -35,15 +28,15 @@ restart() {
 }
 
 case "$1" in
-	start|stop|restart)
-		"$1"
-		;;
-	reload)
-		restart
-		;;
-	*)
-		echo "Usage: $0 {start|stop|restart|reload}"
-		exit 1
+    start|stop|restart)
+	"$1"
+	;;
+    reload)
+	restart
+	;;
+    *)
+	echo "Usage: $0 {start|stop|restart|reload}"
+	exit 1
 esac
 
 exit $?
